### ISSUE TITLE
Bot doesn't know what to do with recursions

### ISSUE THREAD

**Issue by crystalwizard** [PascalRoose/primestatsbot#1]
When reporting stats, the bot reports the number of recursions incorrectly. We've just had an agent who has one recursions use the convertor and while all other stats were reported correctly, the number of recursions was returned as 1,440 <---

Prime Stats ConverterFeb 1, 2020 10:43:21 AM
General
Time Span: ALL TIME 
<stats removed>
Recursion
Recursions: 1,440

**Comment by PascalRoose** [comment]
Turns out 'Umbra: Unique Resonator Slots Deployed' is still visible in 'ALL TIME' stats. This stat has been added to v2.1.1
